### ISSUE TITLE
Branches in different format than KEY-XXX are parsed incorrectly

### ISSUE THREAD

**Issue by rad3ks** [netguru/bitrise-step-slack#11]
Hi!

Let's consider such branch name: `task/test-fix`

The resulting *Task* part in slack message is being parsed incorrectly.

**AS IS**: `[[["test", "fix"]]](https://url.domain/path/[["test", "fix"]])`

My proposal is to omit *Task* segment when branch name doesn't allow to generate it properly. 

**TO BE**: If the format of branch name is not `branch/KEY-XXX` we should not add *Task* segment to slack message.

I want to keep it as bug/enhancement proposal here and just discuss it.

I'm looking forward to see your responses

**Comment by akashivskyy** [comment]
👍, noticed that as well.

**Comment by akashivskyy** [comment]
Fixed in #12, released in [0.4](https://github.com/netguru/bitrise-step-slack/releases/tag/0.4)
